"""initial

Revision ID: 089a452cc1f9
Revises: 
Create Date: 2023-11-24 00:00:57.800391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '089a452cc1f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('sid', sa.BIGINT(), nullable=False),
                    sa.Column('nid', sa.BIGINT(), nullable=True),
                    sa.Column('tid', sa.String(length=128), nullable=True),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('file_id', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('playerscore',
                    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('score', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('user_id', 'id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('switch',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('nid', sa.BIGINT(), nullable=True),
                    sa.Column('asset_tag', sa.BIGINT(), nullable=False),
                    sa.Column('sn', sa.String(length=250), nullable=True),
                    sa.Column('model', sa.String(length=250), nullable=True),
                    sa.Column('name', sa.String(length=250), nullable=True),
                    sa.Column('ipaddres', sa.String(length=250), nullable=True),
                    sa.Column('vlan', sa.String(length=250), nullable=True),
                    sa.Column('upswitch', sa.String(length=250), nullable=True),
                    sa.Column('upport', sa.String(length=250), nullable=True),
                    sa.Column('arenda', sa.String(length=250), nullable=True),
                    sa.Column('type_bc', sa.String(length=250), nullable=True),
                    sa.Column('contact', sa.String(length=250), nullable=True),
                    sa.Column('comment', sa.String(length=250), nullable=True),
                    sa.Column('username', sa.String(length=128), nullable=True),
                    sa.Column('staus', sa.String(length=128), nullable=False),
                    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('username', sa.String(length=128), nullable=True),
                    sa.Column('full_name', sa.String(length=128), nullable=False),
                    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
                    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('user_id', 'id')
                    )
    op.create_table('users2',
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=200), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='user_pk'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('posts2',
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('content', sa.String(length=50), nullable=False),
                    sa.Column('published', sa.String(length=200), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=True),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('title_content_indextitle', 'posts2', ['content'], unique=False)
    # ### end Alembic commands ###

    account = sa.table("users2", sa.column("username", sa.String), sa.column("password", sa.String), sa.column("email", sa.String))

    op.bulk_insert(account, [
        {"username": "John Smith", "password": "123", "email": "1@bk.ru"},
        {"username": "Ed Williams", "password": "123", "email": "2@bk.ru"},
        {"username": "Wendy Jones", "password": "123", "email": "3@bk.ru"},
    ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_content_indextitle', table_name='posts2')
    op.drop_table('posts2')
    op.drop_table('users2')
    op.drop_table('user')
    op.drop_table('switch')
    op.drop_table('playerscore')
    op.drop_table('photo')
    # ### end Alembic commands ###
