"""initial

Revision ID: 66757e34b312
Revises: 
Create Date: 2023-11-24 00:09:10.905056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '66757e34b312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=200), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='user_pk'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('posts2',
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('content', sa.String(length=50), nullable=False),
                    sa.Column('published', sa.String(length=200), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_on', sa.DateTime(), nullable=True),
                    sa.Column('updated_on', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users2.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('title_content_indextitle', 'posts2', ['content'], unique=False)
    # ### end Alembic commands ###
    account = sa.table("users2", sa.column("username", sa.String), sa.column("password", sa.String), sa.column("email", sa.String))

    op.bulk_insert(account, [
        {"username": "John Smith", "password": "123", "email": "1@bk.ru"},
        {"username": "Ed Williams", "password": "123", "email": "2@bk.ru"},
        {"username": "Wendy Jones", "password": "123", "email": "3@bk.ru"},
    ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title_content_indextitle', table_name='posts2')
    op.drop_table('posts2')
    op.drop_table('users2')
    # ### end Alembic commands ###
